### ISSUE TITLE
set permanent download folder

### ISSUE THREAD

**Issue by emmauss** [Tlaster/EHTool#10]
create option to set permanent download folder and use default folder name format

**Comment by emmauss** [comment]
please release update

**Comment by Tlaster** [comment]
unfortunately I can not release the update by uploading to store,it will get a error after Analyzing package,I think the most likely reason is that the preview sdk(10563) contain the build tool which is denied by the store now. So I waiting for the new sdk that can pass the analyzing, or my computer is broken and I have to reset it:)
