### ISSUE TITLE
allow advanced search when searching from tag

### ISSUE THREAD

**Issue by emmauss** [Tlaster/EHTool#13]
when one searches from selecting a tag in a gallery, he cant add other search terms or advanced search to it.it will be good to add something that allows it.

**Comment by Tlaster** [comment]
I think let the user copy the tag value will be better, searching from a tag will navigate to http://exhentai.org/tag/[tag name] which is quite different from searching a key word, if one wants to add other search options, that makes no different from searching a key word, and http://exhentai.org/tag/[tag name] does not accept any parameter like "f_manga=1", it will return the same result whatever the parameter is.

**Comment by emmauss** [comment]
so it is from the api..
